// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import ReactQueryProvider from './ReactQueryProvider'
import '@radix-ui/themes/styles.css'
import { Theme } from '@radix-ui/themes'

export const metadata: Metadata = {
  title: 'Form Task',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <ReactQueryProvider>
            <div>{children}</div>
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  )
}
