// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Form Task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <div>{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
